# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_agent_pb2 as ai__agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClaudeServiceStub(object):
    """============================================================
    서비스 정의
    ============================================================

    Claude 서비스 (Orchestrator)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ai_agent.ClaudeService/HealthCheck',
                request_serializer=ai__agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Process = channel.unary_unary(
                '/ai_agent.ClaudeService/Process',
                request_serializer=ai__agent__pb2.AgentRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.CreatePlan = channel.unary_unary(
                '/ai_agent.ClaudeService/CreatePlan',
                request_serializer=ai__agent__pb2.PlanRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.PlanResponse.FromString,
                _registered_method=True)
        self.GenerateCode = channel.unary_unary(
                '/ai_agent.ClaudeService/GenerateCode',
                request_serializer=ai__agent__pb2.GenerateCodeRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.GenerateCodeResponse.FromString,
                _registered_method=True)
        self.Orchestrate = channel.unary_unary(
                '/ai_agent.ClaudeService/Orchestrate',
                request_serializer=ai__agent__pb2.OrchestrateRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.OrchestrateResponse.FromString,
                _registered_method=True)
        self.StreamPlan = channel.unary_stream(
                '/ai_agent.ClaudeService/StreamPlan',
                request_serializer=ai__agent__pb2.PlanRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.StreamMessage.FromString,
                _registered_method=True)


class ClaudeServiceServicer(object):
    """============================================================
    서비스 정의
    ============================================================

    Claude 서비스 (Orchestrator)
    """

    def HealthCheck(self, request, context):
        """헬스 체크
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request, context):
        """범용 처리
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlan(self, request, context):
        """계획 수립
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCode(self, request, context):
        """코드 생성
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Orchestrate(self, request, context):
        """오케스트레이션
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPlan(self, request, context):
        """스트리밍 계획 수립
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClaudeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__agent__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=ai__agent__pb2.AgentRequest.FromString,
                    response_serializer=ai__agent__pb2.AgentResponse.SerializeToString,
            ),
            'CreatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlan,
                    request_deserializer=ai__agent__pb2.PlanRequest.FromString,
                    response_serializer=ai__agent__pb2.PlanResponse.SerializeToString,
            ),
            'GenerateCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCode,
                    request_deserializer=ai__agent__pb2.GenerateCodeRequest.FromString,
                    response_serializer=ai__agent__pb2.GenerateCodeResponse.SerializeToString,
            ),
            'Orchestrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Orchestrate,
                    request_deserializer=ai__agent__pb2.OrchestrateRequest.FromString,
                    response_serializer=ai__agent__pb2.OrchestrateResponse.SerializeToString,
            ),
            'StreamPlan': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPlan,
                    request_deserializer=ai__agent__pb2.PlanRequest.FromString,
                    response_serializer=ai__agent__pb2.StreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_agent.ClaudeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_agent.ClaudeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClaudeService(object):
    """============================================================
    서비스 정의
    ============================================================

    Claude 서비스 (Orchestrator)
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.ClaudeService/HealthCheck',
            ai__agent__pb2.HealthCheckRequest.SerializeToString,
            ai__agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.ClaudeService/Process',
            ai__agent__pb2.AgentRequest.SerializeToString,
            ai__agent__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.ClaudeService/CreatePlan',
            ai__agent__pb2.PlanRequest.SerializeToString,
            ai__agent__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.ClaudeService/GenerateCode',
            ai__agent__pb2.GenerateCodeRequest.SerializeToString,
            ai__agent__pb2.GenerateCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Orchestrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.ClaudeService/Orchestrate',
            ai__agent__pb2.OrchestrateRequest.SerializeToString,
            ai__agent__pb2.OrchestrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_agent.ClaudeService/StreamPlan',
            ai__agent__pb2.PlanRequest.SerializeToString,
            ai__agent__pb2.StreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GeminiServiceStub(object):
    """Gemini 서비스 (Analyst)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ai_agent.GeminiService/HealthCheck',
                request_serializer=ai__agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Process = channel.unary_unary(
                '/ai_agent.GeminiService/Process',
                request_serializer=ai__agent__pb2.AgentRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.Analyze = channel.unary_unary(
                '/ai_agent.GeminiService/Analyze',
                request_serializer=ai__agent__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.ReviewCode = channel.unary_unary(
                '/ai_agent.GeminiService/ReviewCode',
                request_serializer=ai__agent__pb2.ReviewCodeRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.ReviewCodeResponse.FromString,
                _registered_method=True)
        self.Research = channel.unary_unary(
                '/ai_agent.GeminiService/Research',
                request_serializer=ai__agent__pb2.ResearchRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.ResearchResponse.FromString,
                _registered_method=True)
        self.StreamAnalyze = channel.unary_stream(
                '/ai_agent.GeminiService/StreamAnalyze',
                request_serializer=ai__agent__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.StreamMessage.FromString,
                _registered_method=True)


class GeminiServiceServicer(object):
    """Gemini 서비스 (Analyst)
    """

    def HealthCheck(self, request, context):
        """헬스 체크
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request, context):
        """범용 처리
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request, context):
        """분석
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReviewCode(self, request, context):
        """코드 리뷰
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Research(self, request, context):
        """리서치
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnalyze(self, request, context):
        """스트리밍 분석
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeminiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__agent__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=ai__agent__pb2.AgentRequest.FromString,
                    response_serializer=ai__agent__pb2.AgentResponse.SerializeToString,
            ),
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=ai__agent__pb2.AnalyzeRequest.FromString,
                    response_serializer=ai__agent__pb2.AnalyzeResponse.SerializeToString,
            ),
            'ReviewCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ReviewCode,
                    request_deserializer=ai__agent__pb2.ReviewCodeRequest.FromString,
                    response_serializer=ai__agent__pb2.ReviewCodeResponse.SerializeToString,
            ),
            'Research': grpc.unary_unary_rpc_method_handler(
                    servicer.Research,
                    request_deserializer=ai__agent__pb2.ResearchRequest.FromString,
                    response_serializer=ai__agent__pb2.ResearchResponse.SerializeToString,
            ),
            'StreamAnalyze': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAnalyze,
                    request_deserializer=ai__agent__pb2.AnalyzeRequest.FromString,
                    response_serializer=ai__agent__pb2.StreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_agent.GeminiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_agent.GeminiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeminiService(object):
    """Gemini 서비스 (Analyst)
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.GeminiService/HealthCheck',
            ai__agent__pb2.HealthCheckRequest.SerializeToString,
            ai__agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.GeminiService/Process',
            ai__agent__pb2.AgentRequest.SerializeToString,
            ai__agent__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.GeminiService/Analyze',
            ai__agent__pb2.AnalyzeRequest.SerializeToString,
            ai__agent__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReviewCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.GeminiService/ReviewCode',
            ai__agent__pb2.ReviewCodeRequest.SerializeToString,
            ai__agent__pb2.ReviewCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Research(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.GeminiService/Research',
            ai__agent__pb2.ResearchRequest.SerializeToString,
            ai__agent__pb2.ResearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAnalyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_agent.GeminiService/StreamAnalyze',
            ai__agent__pb2.AnalyzeRequest.SerializeToString,
            ai__agent__pb2.StreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CodexServiceStub(object):
    """Codex 서비스 (Executor)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ai_agent.CodexService/HealthCheck',
                request_serializer=ai__agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Process = channel.unary_unary(
                '/ai_agent.CodexService/Process',
                request_serializer=ai__agent__pb2.AgentRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/ai_agent.CodexService/Execute',
                request_serializer=ai__agent__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Build = channel.unary_unary(
                '/ai_agent.CodexService/Build',
                request_serializer=ai__agent__pb2.BuildRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.BuildResponse.FromString,
                _registered_method=True)
        self.Test = channel.unary_unary(
                '/ai_agent.CodexService/Test',
                request_serializer=ai__agent__pb2.TestRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.TestResponse.FromString,
                _registered_method=True)
        self.Deploy = channel.unary_unary(
                '/ai_agent.CodexService/Deploy',
                request_serializer=ai__agent__pb2.DeployRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.DeployResponse.FromString,
                _registered_method=True)
        self.StreamExecute = channel.unary_stream(
                '/ai_agent.CodexService/StreamExecute',
                request_serializer=ai__agent__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=ai__agent__pb2.StreamMessage.FromString,
                _registered_method=True)


class CodexServiceServicer(object):
    """Codex 서비스 (Executor)
    """

    def HealthCheck(self, request, context):
        """헬스 체크
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request, context):
        """범용 처리
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """명령 실행
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Build(self, request, context):
        """빌드
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Test(self, request, context):
        """테스트
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deploy(self, request, context):
        """배포
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExecute(self, request, context):
        """스트리밍 실행 (실시간 로그)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__agent__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=ai__agent__pb2.AgentRequest.FromString,
                    response_serializer=ai__agent__pb2.AgentResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=ai__agent__pb2.ExecuteRequest.FromString,
                    response_serializer=ai__agent__pb2.ExecuteResponse.SerializeToString,
            ),
            'Build': grpc.unary_unary_rpc_method_handler(
                    servicer.Build,
                    request_deserializer=ai__agent__pb2.BuildRequest.FromString,
                    response_serializer=ai__agent__pb2.BuildResponse.SerializeToString,
            ),
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=ai__agent__pb2.TestRequest.FromString,
                    response_serializer=ai__agent__pb2.TestResponse.SerializeToString,
            ),
            'Deploy': grpc.unary_unary_rpc_method_handler(
                    servicer.Deploy,
                    request_deserializer=ai__agent__pb2.DeployRequest.FromString,
                    response_serializer=ai__agent__pb2.DeployResponse.SerializeToString,
            ),
            'StreamExecute': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamExecute,
                    request_deserializer=ai__agent__pb2.ExecuteRequest.FromString,
                    response_serializer=ai__agent__pb2.StreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_agent.CodexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_agent.CodexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodexService(object):
    """Codex 서비스 (Executor)
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.CodexService/HealthCheck',
            ai__agent__pb2.HealthCheckRequest.SerializeToString,
            ai__agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.CodexService/Process',
            ai__agent__pb2.AgentRequest.SerializeToString,
            ai__agent__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.CodexService/Execute',
            ai__agent__pb2.ExecuteRequest.SerializeToString,
            ai__agent__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Build(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.CodexService/Build',
            ai__agent__pb2.BuildRequest.SerializeToString,
            ai__agent__pb2.BuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.CodexService/Test',
            ai__agent__pb2.TestRequest.SerializeToString,
            ai__agent__pb2.TestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deploy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_agent.CodexService/Deploy',
            ai__agent__pb2.DeployRequest.SerializeToString,
            ai__agent__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_agent.CodexService/StreamExecute',
            ai__agent__pb2.ExecuteRequest.SerializeToString,
            ai__agent__pb2.StreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
